import { configDotenv } from 'dotenv';
configDotenv()
import { ObjectId } from 'mongodb';
import { createTransport } from 'nodemailer';

// Config nodemailer (backup)
// const transporter = createTransport({
//   service: 'ocean-combat.com',
//   auth: {
//     user: process.env.MAIL_USER,
//     pass: process.env.MAIL_PASS
//   }
// });

// Config of nodemailer [This code part has been generated by AI]
const transporter = createTransport({
  host: 'smtp.ionos.de',
  port: 587, 
  secure: true, 
  auth: {
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASS
  }
});

export async function sendVerificationEmail(userId: ObjectId, email: string): Promise<boolean> {
  const currentUrl = "http://18.199.96.57:3001/api/verification/";
  const mailOptions = {
    from: process.env.MAIL_USER,
    to: email,
    subject: "Verify your e-mail",
    html:
      `<p>Verify your email address to html :	complete the signup and login into your account.</p><p>This link
    <b>expires in 6	</b><a href=${currentUrl + userId}>here</a>to proceed</p>`
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log("We sent your mail");
    return true;
  } catch (e) {
    console.error(e);
    return false;
  }
}