import { model, Model, Schema } from "mongoose"
import bcrypt from "bcryptjs"
import { ExpirationTime } from "../Resources";
import { ObjectId } from "mongodb";

interface IUserMethods {
    isCorrectPassword(toCheck: string): Promise<boolean>
};

type UserModel = Model<IUser, {}, IUserMethods>;

// User interface
export interface IUser {
    _id: ObjectId;          // MongoDB ID-type (generated by mongodb)
    email: string
    username: string,
    password: string,
    points: number,
    team?: number,          // Used in frontend in teams- or ffa-mode otherwise it's empty by default (e.g. 1vs1)
    //picture?: string,                         NICE TO HAVE
    premium: boolean,
    level: number,
    gameSound: number,
    music: number,
    higherLvlChallenge: boolean,
    verified: boolean,
    verificationTimer: Date,
    skin: string
};

// User schema
const userSchema = new Schema<IUser, UserModel, IUserMethods>({
    _id: { type: ObjectId, auto: true },           // MongoDB ID-type (generated by mongodb)
    email: { type: String, required: true, unique: true },
    username: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    points: { type: Number, default: 0 },
    team: { type: Number },   // Used in frontend in teams- or ffa-mode otherwise it's empty by default (e.g. 1vs1)
    //picture: {type: String, default: ""},     NICE TO HAVE
    premium: { type: Boolean, default: false },
    level: { type: Number, default: 0 },
    gameSound: { type: Number, default: 0.3 },
    music: { type: Number, default: 0.3 },
    higherLvlChallenge: { type: Boolean, default: false },
    verified: { type: Boolean, default: false },
    verificationTimer: { type: Date, default: Date.now() + ExpirationTime.TwentyFourHours }, // Check enum ExpirationTime in Resources
    skin: {type: String, default: "standard"}
});

userSchema.pre("save", async function () {
    if (this.isModified("password")) {
        const hashedPassword = await bcrypt.hash(this.password, 10);
        this.password = hashedPassword;
    }
});

userSchema.pre(["updateOne", "findOneAndUpdate", "updateMany"], async function () {
    const update = this.getUpdate();
    if (update && "password" in update) {
        const hashedPassword = await bcrypt.hash(update.password, 10);
        update.password = hashedPassword;
    }
});

userSchema.method("isCorrectPassword", function (toCheck: string): Promise<boolean> {
    if (this.isModified("password")) {
        throw new Error("Error! Can't compare password, some updates aren't yet saved.")
    }
    const isCorrect = bcrypt.compare(toCheck, this.password);
    return isCorrect;
});

export const User = model("User", userSchema);